// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAxUwLh7dMsYcpP_0Oc32n0D0PN1_EXUo',
    appId: '1:616246481846:web:04e5b9e83d2a0888062717',
    messagingSenderId: '616246481846',
    projectId: 'opkoko-flutter-co-creation',
    authDomain: 'opkoko-flutter-co-creation.firebaseapp.com',
    storageBucket: 'opkoko-flutter-co-creation.appspot.com',
    measurementId: 'G-95YW055H4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_5hmhWxkmlDTCnXfbTLjJOdh1w9wIUrE',
    appId: '1:616246481846:android:87a8d32af74b83ba062717',
    messagingSenderId: '616246481846',
    projectId: 'opkoko-flutter-co-creation',
    storageBucket: 'opkoko-flutter-co-creation.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe5ANca0qr5c6My_rJoC9iTKdfVfnxMOs',
    appId: '1:616246481846:ios:9ad450f003945f2f062717',
    messagingSenderId: '616246481846',
    projectId: 'opkoko-flutter-co-creation',
    storageBucket: 'opkoko-flutter-co-creation.appspot.com',
    iosClientId: '616246481846-ea6cv99ijs25vmj2uoh08o018cfqmc2g.apps.googleusercontent.com',
    iosBundleId: 'com.example.opkokoFlutterCoCreation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe5ANca0qr5c6My_rJoC9iTKdfVfnxMOs',
    appId: '1:616246481846:ios:9ad450f003945f2f062717',
    messagingSenderId: '616246481846',
    projectId: 'opkoko-flutter-co-creation',
    storageBucket: 'opkoko-flutter-co-creation.appspot.com',
    iosClientId: '616246481846-ea6cv99ijs25vmj2uoh08o018cfqmc2g.apps.googleusercontent.com',
    iosBundleId: 'com.example.opkokoFlutterCoCreation',
  );
}
